apiVersion: apps/v1
kind: Deployment
metadata:
  name: b4bookalbum
  labels:
    app: b4bookalbum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: b4bookalbum
  template:
    metadata:
      labels:
        app: b4bookalbum
    spec:
      containers:
      - name: b4bookalbum
        image: sreedocker123/bookmoviealbum:latest
        ports:
        - containerPort: 80
