apiVersion: v1
kind: Service
metadata:
  labels:
    app: b4bookalbum
  name: b4bookalbum
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: b4bookalbum

